<div class="parallax-container">
  <img class="img-planes" src="<?php echo BASE_URL ?>public/img/black-and-white-city-skyline-buildings.jpg">
  <h4 class="white-text absulut-title">
    Cuenta
  </h4>
</div>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#mensaje"><span class="icon-tabcontrol icon-mail5"></span>Mensajes</a></li>
      <li class="tab col s3"><a class="" href="#notificaciones"><span class="icon-tabcontrol icon-notification2"></span>Notificaciones</a></li>
    </ul>
  </div>
  <div id="mensaje" class="content-tab col s12">
    <section class="content-mensajes container">
      <ul class="collapsible popout" data-collapsible="accordion">
        <?php for ($i=0; $i < count($this->mensaje); $i++) { ?>
          <li class="">
            <div class="white-text brown darken-4 collapsible-header center-align"><i class="icon-contact_mail"></i><?php echo $this->mensaje[$i]['mensaje_nombre'].' '.$this->mensaje[$i]['mensaje_apellido'] ; ?></div>
            <div class="collapsible-body container">
              <div class="margin-msn">
                <div><strong>Asunto</strong></div>
                <span><?php echo $this->mensaje[$i]['mensaje_asunto']?></span>
              </div>
              <div class="margin-msn">
                <div><strong>E-mail</strong></div>
                <span><?php echo $this->mensaje[$i]['mensaje_email']?></span>
              </div>
              <div class="margin-msn">
                <div><strong>Mensaje</strong></div>
                <span><?php echo $this->mensaje[$i]['mensaje_mensaje']?></span>
              </div>
            </div>
          </li>
        <?php } ?>
      </ul>
    </section>
  </div>
  <div id="notificaciones" class="content-tab col s12">
    <section class="content-mensajes container">
      <ul class="collapsible popout" data-collapsible="accordion">
        <?php for ($i=0; $i < count($this->empresa); $i++) { ?>
          <li class="">
            <div class="white-text brown darken-4 collapsible-header center-align"><i class="icon-contact_mail"></i><?php echo $this->empresa[$w]['nombre'] ?></div>
            <div class="collapsible-body container_empresa row">
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Dir. Oficina central</strong></div>
                <span><?php echo $this->empresa[$w]['oficina_central'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Fundacion</strong></div>
                <span><?php echo $this->empresa[$w]['fundacion'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Presidente</strong></div>
                <span><?php echo $this->empresa[$w]['presidente'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>No. empleados</strong></div>
                <span><?php echo $this->empresa[$w]['numero_de_empleados'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Dir. Plantas industriales</strong></div>
                <span><?php echo $this->empresa[$w]['principales_operaciones'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Principales operaciones</strong></div>
                <span><?php echo $this->empresa[$w]['plantas_industriales'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Dir. Oficina de contacto</strong></div>
                <span><?php echo $this->empresa[$w]['oficinas_de_contacto'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Tipo de sociedad</strong></div>
                <span><?php echo $this->empresa[$w]['tipo_sociedad'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Rut</strong></div>
                <span><?php echo $this->empresa[$w]['rut'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Tipos de producto</strong></div>
                <span><?php ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Dir. domicilio legal</strong></div>
                <span><?php echo $this->empresa[$w]['domicilio_legal'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Dir. Domicilio comercial</strong></div>
                <span><?php echo $this->empresa[$w]['domicilio_comercial'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Telefonos</strong></div>
                <span><?php echo $this->empresa[$w]['telefonos'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Fax</strong></div>
                <span><?php echo $this->empresa[$w]['fax'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>E-mail</strong></div>
                <span><?php echo $this->empresa[$w]['e_mail'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Departamento</strong></div>
                <span><?php  ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Municipio</strong></div>
                <span><?php echo $this->empresa[$w]['municipio_nombre'] ?></span>
              </div>
              <div class="margin-msn col s12 m6 l4">
                <div><strong>Tipo de empresa</strong></div>
                <span><?php echo $this->empresa[$w]['tipo_empresa_idtipo_empresa'] ?></span>
              </div>
                <button id="btn-solicitudes" class="btn waves-effect transparent btn-contacto">Aceptar</button>
            </div>
          </li>
        <?php } ?>
      </ul>
    </section>
  </div>
</div>