<div class="content_tabs_">
<div class="close_content_tab"></div>
<div class="card_content_tab white z-depth-2">
  <ul class="collapsible popout" data-collapsible="accordion">
      <li class="">
        <div class="white-text brown darken-4 collapsible-header center-align"><i class="icon-contact_mail"></i><span class="nombre_apellido"></span></div>
        <div class="collapsible-body container">
          <div class="margin-msn">
            <div><strong>Asunto</strong></div>
            <span id="asunto_mensaje"></span>
          </div>
          <div class="margin-msn">
            <div><strong>E-mail</strong></div>
            <span id="email_mensaje"></span>
          </div>
          <div class="margin-msn">
            <div><strong>Mensaje</strong></div>
            <span id="mensaje_mensaje"></span>
          </div>
        </div>
      </li>
  </ul>
</div>
</div>

<div class="parallax-container">
  <img class="img-planes" src="<?php echo BASE_URL ?>public/img/black-and-white-city-skyline-buildings.jpg">
  <h4 class="white-text absulut-title">
    Cuenta
  </h4>
</div>
<div class="row">
  <div class="col s12 padding_tab">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#mensaje"><span class="icon-tabcontrol icon-mail5"></span><span class="text_icon-tab">Mensajes</span></a></li>
      <li class="tab col s3"><a class="" href="#notificaciones"><span class="icon-tabcontrol icon-notification2"></span><span class="text_icon-tab">Notificaciones</span></a></li>
    </ul>
  </div>
  <div id="mensaje" class="content-tab col s12">
    <section class="content-mensajes container">
      <div class="container_taget_notifications z-depth-2">
        <h4 class="center-align">Mensajes</h4>
        
        <form class="form_margin_mensaje " id="ver_mensaje">
          <div  class="input-field col s12 m12 l12">
            <select  id="name_depato" name="mensaje">
              <option value="" disabled selected>Elija una opcion</option>
              <?php for ($h=0; $h < count($this->mensaje) ; $h++) { ?>
                <option value="<?php echo $this->mensaje[$h]['idmensaje']; ?>"><?php echo $this->mensaje[$h]['mensaje_nombre'].' '.$this->mensaje[$h]['mensaje_apellido']; ?></option>
              <?php } ?>
            </select>
            <label>Nombre</label>
          </div>
          <button class="btn waves-effect transparent btn-contacto_ver" type="submit" name="ver_nensaje">Ver mensajes</button>
        </form> 

      </div>
    </section>
  </div>
  <div id="notificaciones" class="content-tab col s12">
    <section class="content-mensajes container">
      <div class="container_taget_notifications z-depth-2">
        <h4 class="center-align">Solicitudes</h4>
        
        <form class="form_margin_rut" id="ver_solicitud aceptar_solicitud">
          <div class="input-field col s12 m12 l12">
            <select  id="name_depato" name="departamento">
              <option value="" disabled selected>Elija una opcion</option>
              <?php for ($h=0; $h < count($this->empresa) ; $h++) { ?>
                <option value="<?php echo $this->empresa[$h]['rut']; ?>"><?php echo $this->empresa[$h]['rut']; ?></option>
              <?php } ?>
            </select>
            <label>Rut Empresa</label>
          </div>
          <button class="btn waves-effect transparent btn-contacto_ver" type="submit" name="aceptar">Aceptar solicitud</button>
        </form> 

      </div>
    </section>
  </div>
</div>