<div class="parallax-container">
  <img class="img-planes" src="<?php echo BASE_URL ?>public/img/black-and-white-city-skyline-buildings.jpg">
  <h4 class="white-text absulut-title">
    Cuenta
  </h4>
</div>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#mensaje"><span class="icon-tabcontrol icon-mail5"></span>Mensajes</a></li>
      <li class="tab col s3"><a class="" href="#notificaciones"><span class="icon-tabcontrol icon-notification2"></span>Notificaciones</a></li>
    </ul>
  </div>
  <div id="mensaje" class="content-tab col s12">
    <section class="content-mensajes container">
      <ul class="collapsible popout" data-collapsible="accordion">
        <?php for ($i=0; $i < 10; $i++) { ?>
          <li class="">
            <div class="collapsible-header center-align"><i class="icon-contact_mail"></i>Nombre y apellido del contacto</div>
            <div class="collapsible-body container">
              <div class="margin-msn">
                <div><strong>Asunto</strong></div>
                <span>Un asunto para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>E-mail</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Mensaje</strong></div>
                <span>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</span>
              </div>
            </div>
          </li>
        <?php } ?>
      </ul>
    </section>
  </div>
  <div id="notificaciones" class="content-tab col s12">
    <section class="content-mensajes container">
      <ul class="collapsible popout" data-collapsible="accordion">
        <?php for ($i=0; $i < 10; $i++) { ?>
          <li class="">
            <div class="collapsible-header center-align"><i class="icon-contact_mail"></i>Nombre de la empresa</div>
            <div class="collapsible-body container">
              <div class="margin-msn">
                <div><strong>Dir. Oficina central</strong></div>
                <span>Un asunto para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Fundacion</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Presidente</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>No. empleados</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Dir. Plantas industriales</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Principales operaciones</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Dir. Oficina de contacto</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Tipo de sociedad</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Rut</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Tipos de producto</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Dir. domicilio legal</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Dir. Domicilio comercial</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Telefonos</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Fax</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>E-mail</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Departamento</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Municipio</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
              <div class="margin-msn">
                <div><strong>Tipo de empresa</strong></div>
                <span>Un e-mail para la administracion</span>
              </div>
            </div>
          </li>
          
        <?php } ?>
      </ul>
    </section>
  </div>
</div>