<section class="row">
	<div class="col s12 m12 l12 row">
		<figure class="col s12 m12 l6">
			<img class="responsive-img" src="<?php echo BASE_URL ?>public/img/pexels-photo.jpg?>">
		</figure>
		<article class="col s12 m12 l6 section-card">
			<div class="white-text teal darken-4 carta-principal z-depth-2">
				<article>
		        	<div class="texto-card-sevices">
						<h4>!Trabaja con nosotros¡</h4>
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div white black-text">
		        			<span class="icon-school icon-logo-unete"></span>
		        		</div>
		        	</div>
			      <div class="card-content">
			        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>Acompañanos a conecrtar al mundo</strong></div>
			      </div>
		        </article>
			</div>
		</article>
	</div>
	<div class="col s12 m12 l12 row">
		<article class="col s12 m12 l6 section-card">
			<div class="white-text teal darken-4 carta-principal z-depth-2">
				<article>
		        	<div class="texto-card-sevices">
						Si eres responsable con habilidades técnicas y de programación de interfaz web enfocado a Responsive Web Design  y Material Design con habilidades en diagramación de la estructura semántica de contenidos e interacciones con usuarios
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div white black-text">
		        			<span class="icon-devices_other icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
			</div>
		</article>
		<figure class="col s12 m12 l6">
			<img class="responsive-img" src="<?php echo BASE_URL ?>public/img/startup-photos.jpg">
		</figure>
	</div>
	<div class="col s12 m12 l12 row">
		<figure class="col s12 m12 l6">
			<img class="responsive-img" src="<?php echo BASE_URL ?>public/img/startup-photos1.jpg">
		</figure>
		<article class="col s12 m12 l6 section-card">
			<div class="white-text teal darken-4 carta-principal z-depth-2">
				<article>
		        	<div class="texto-card-sevices">
						Manejas html5, css3,
						Javascript, jQuery,
						eres creativo, visualizas animaciones transiciones y cambios en aplicaciones de estilo visual en código
						dominas normatividad para la construcción de HTML, dictados por la W3C,
						manejas de elementos visuales de un sitio web.
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div white black-text">
		        			<span class="icon-html-five icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong><a href="<?php echo BASE_URL?>contacto">Contactanos</a></strong></div>
		      </div>
			</div>
		</article>
	</div>
</section>

