<div class="container-info row container">
	<?php for ($i=0; $i < count($this->productos); $i++) { ?>
		<div class="container-pading col s12 m6 l4">
			<div class="card">
				<div title="<?php echo $this->productos[$i]['producto_nombre']; ?>" class="Titulo-articulo center-align" ><?php echo $this->productos[$i]['producto_nombre']; ?></div>
				<div title="<?php echo $this->productos[$i]['producto_valor']; ?>" class="title-valor center-align"><?php echo $this->productos[$i]['producto_valor'] ?></div>
			  	<div class="container-item-img" >
					<img title="<?php echo $this->productos[$i]['producto_nombre']; ?>" alt="<?php echo $this->productos[$i]['producto_nombre']; ?>" class="img-item" src="<?php echo BASE_URL.'public/img/productos/'.$this->productos[$i]['fotos_name'] ?>">
				</div>
				<div class="card-content">
				  	<div class="activator center-align padding-arrow">
						<span title="Descripcion del producto" class="activator icon-arrow-bold-right green darken-4 white-text"></span>
					</div>
				</div>
				<div class="card-reveal">
				  <span title="Caracteristicas" class="card-title grey-text text-darken-4"><strong>Caracteristicas</strong><i class="icon-keyboard_arrow_down right"></i></span>
				  <p><?php echo $this->productos[$i]['producto_descripcion'] ?></p>
				</div>
			</div>
		</div>
	<?php } ?>
</div>
