<div class="buscador">

  <form id="buscar-form-serach" class="container row">
    	<div class="input-field col s12 m12 l6">
        <input id="first_name" type="text" class="validate">
        <label for="first_name">¿Que buscas?</label>
      </div>
      <div class="input-field col s12 m6 l2">
        <select  class="browser-default" id="google_name_depato" name="departamento">
          <option value="" disabled selected>Elija una departamento</option>
        <?php for ($h=0; $h < count($this->dpts) ; $h++) { ?>
          <option value="<?php echo $this->dpts[$h]['iddepartamento']; ?>"><?php echo $this->dpts[$h]['nombre']; ?></option>
        <?php } ?>
        </select>
      </div>
    <div class="input-field col s12 m6 l2">
      <select class="browser-default" id="name_mun" name="tipo_de_empresa">
        <option value="" disabled selected>Elija un tipo de empresa</option>
        <?php for ($w=0; $w < count($this->tipo) ; $w++) { ?>
          <option value="<?php echo $this->tipo[$w]['idtipo_empresa']; ?>"><?php echo ucfirst(strtolower($this->tipo[$w]['tipo_empresa_nombre'])); ?></option>
        <?php } ?>
      </select>
    </div>
    <div class="input-field col s12 m6 l2">
      <select class="browser-default" name="tienda">
        <option value="" disabled selected>Tienda</option>
        <?php for ($x=0; $x < count($this->tienda) ; $x++) { ?>
          <option value="<?php echo $this->tienda[$x]['idempresa']; ?>"><?php echo ucfirst(strtolower($this->tienda[$x]['empresaname'])); ?></option>
        <?php } ?>
      </select>
    </div>
    <button class="btn waves-effect teal darken-3 col s12 m12 l12" type="submit" name="action">Buscar</button>
  </form>
</div>
<div class="resutados row">
<?php 
      if (isset($this->empresa) && count($this->empresa)) { ?>

        <div class="col s12 m12 l12 cont-items">
          <?php for ($i=0; $i < count($this->empresa) ; $i++) { ?>
            <div class="row col s12 m6 l4">
              <div class="card col s12 m12 l12">
                <div class="card-image waves-effect waves-block waves-light">
                  <img alt="<?php echo $this->empresa[$i]['empresaname'] ?>" title="<?php echo $this->empresa[$i]['empresaname'] ?>" class="activator" src="<?php echo BASE_URL.'public/img/perfilesweb/pulpas_madretierra.jpg' ?>">
                </div>
                <div class="card-content">
                  <div class="card-title activator grey-text text-darken-4 center-align"><strong><?php echo ucfirst($this->empresa[$i]['empresaname']); ?></strong></div>
                  <p><a href="<?php echo BASE_URL.strtolower(str_replace(' ', '', $this->empresa[$i]['empresaname'])) ?>"><?php echo 'www.'.strtolower(str_replace(' ', '', $this->empresa[$i]['empresaname'])).'.com'; ?></a></p>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4"><strong><?php echo ucfirst($this->empresa[$i]['empresaname']); ?></strong><i class="icon-close right"></i></span>
                  <p>
                    <?php 
                      echo '<strong>Oficina central</strong>: '. ucfirst($this->empresa[$i]['oficina_central']); 
                      echo '<br><strong>Principales operaciones</strong>: '. ucfirst($this->empresa[$i]['principales_operaciones']); 
                      echo '<br><strong>Tipo de productos</strong>: '. ucfirst($this->empresa[$i]['empresa_tipo_productos']); 
                      echo '<br><strong>Telefonos</strong>: '. ucfirst($this->empresa[$i]['telefonos']);
                      echo '<br><strong>E-mail</strong>: '. ucfirst($this->empresa[$i]['e_mail']);
                      echo '<br><strong>Municipio</strong>: '. ucfirst($this->empresa[$i]['muname']);
                    ?>
                  </p>
                </div>
              </div>
            </div>
          <?php  } ?> 
        </div>

<?php }else{ ?>
    <h5 class="center-align"><strong>Aun no hay registros en la base de datos</strong></h5>
<?php } ?>
</div>
<?php if (isset($this->paginacion)) {
    echo $this->paginacion;
} ?>