<div class="parallax-container">
    <div class="parallax"><img src="<?php BASE_URL ?>public/img/black-and-white-city-man-people.jpg"></div>
</div>
<section class="container card nosotros-card">
<h3>Nosotros</h3>
	Em-conecta es una empresa dedicada a ofrecer servicios de organización de datos empresariales como productos o servicios, nos orientamos por la definición de sistemas de información para obtener datos confiables y de esta manera poder orientar correctamente a nuestros clientes ya que los sistemas de información junto a tecnologías de información cambiaron la forma de operación de las organizaciones actuales.
	Obtener la información precisa que busca un cliente es muy importante ya que optimiza el tiempo del empresario el cual se puede utilizar para otras labores de mejoramiento de la empresa. Por esta razón nos preocupamos por entregarle al posible comprador esta información
	Nos encargamos de brindar estadísticas que orienten a tu empresa en una correcta toma de decisiones para que de esta forma tengas una excelente administración de tu empresa.
</section>
<div class="row container">
	<div class="col s12 m12 l6">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Mision</strong></h4>
	        	<div class="texto-card-sevices">
	        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-database icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	      <div class="card-content">
	        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
	      </div>
	    </div>
    </div>
	<div class="col s12 m12 l6">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Vision</strong></h4>
	        	<div class="texto-card-sevices">
	        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-database icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	      <div class="card-content">
	        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
	      </div>
	    </div>
    </div>
</div>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/desk-office-hero-workspace.jpg"></div>
</div>
<div class="row container">
    <div class="col s12 m12 l12">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>En que creemos</strong></h4>
	        	<div class="texto-card-sevices">
	        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-database icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	      <div class="card-content">
	        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
	      </div>
	    </div>
    </div>
</div>