<div class="parallax-container">
    <div class="parallax"><img src="<?php BASE_URL ?>public/img/black-and-white-city-man-people.jpg"></div>
</div>
<section class="container card nosotros-card">
<h3>Nosotros</h3>
	<?php echo $this->configuracion['otros_nosotros'] ?>
</section>
<div class="row container">
	<div class="col s12 m12 l6">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Mision</strong></h4>
	        	<div class="texto-card-sevices">
	        		<?php echo $this->configuracion['otros_mision'] ?>
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-favorite icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	    </div>
    </div>
	<div class="col s12 m12 l6">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Vision</strong></h4>
	        	<div class="texto-card-sevices">
	        		<?php echo $this->configuracion['otros_vision']; ?>
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-eye2 icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	    </div>
    </div>
</div>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/desk-office-hero-workspace.jpg"></div>
</div>
<div class="row container">
    <div class="col s12 m12 l12">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>En que creemos</strong></h4>
	        	<div class="texto-card-sevices">
	        		<?php echo $this->configuracion['otros_en_que_creemos']; ?>
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-pan_tool icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	    </div>
    </div>
</div>