<section class="section-card">
	<div class="white-text teal darken-4 carta-principal z-depth-2">
		<article>
        	<div class="texto-card-sevices">
        		Conéctate con todo Colombia sin esfuerzo, posiciónate en la web, haz que tus clientes encuentren lo que buscan, crea nuevas opciones de negocio con el análisis de mercado que te proporciona em-conecta.<br> !Tu futuro en la web¡
        	</div>
        	<div class="radio-icon">
        		<div class="radio-div white black-text">
        			<span class="icon-power-plug icon-logo-unete"></span>
        		</div>
        	</div>
	    	<div class="card-content">
	    		<div class="card-title activator blue-text text-darken-1 center-align"><strong>Conecta al mundo</strong></div>
	    	</div>
        </article>
	</div>
</section>
<section>
	<h3 class="center-align">Efectividad</h3>
</section>
<section class="text-info-publica">
	<p class="container">
		<span class="inicio-text blue-text text-darken-1">E</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		n todas las empresas se constituye un sistema social, este sistema está construido por grupos de discorde naturaleza dado este concepto podemos decir que los grupos son dinámicos porque cambian todo el tiempo. Para que estos grupos funcionen es necesario asignarles roles para realizar todas las actividades de la empresa.
		En la actualidad la tecnología se suma a los recursos con los que cuentan estos grupos de trabajo para desarrollar estas actividades. Dado este aspecto es imposible negar que el comportamiento social se separe de esta herramienta.
		Un método concluyente en el cual una empresa alcance la efectividad no existe dado que esta se puntualiza al logro de objetivos y se relaciona con un resultado, de acuerdo a esto podemos decir que cada empresa debe buscar un equilibrio entre al alcance de sus objetivos, satisfacción de los integrantes y el funcionamiento.
		El diccionario de administración y finanzas nos dice que la efectividad es la organización optima entre cinco elementos: producción, eficiencia, satisfacción, adaptabilidad y desarrollo.
		Modificar las estructuras organizativas al igual que el comportamiento organizacional y los sistemas de trabajo para que los empleados tengan mayor autonomía en la resolución de problemas y toma de decisiones mejoran la efectividad de las empresas.
		Las empresas son entes vivos, ya que en su funcionamiento tiene incrustado la conducta de las personas que la forman, la efectividad se logra mediante una conducta motivada, buena comunicación y el trabajo en equipo para el logro de objetivos. 
	</p>
</section>
<div class="parallax-container margin-paralax">
    <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/person-apple-laptop-notebook.jpg"></div>
</div>
<section>
	<h3 class="center-align">Servicios</h3>
</section>
<section class="text-info-publica">
	<article class="container row">
		<div class="col s12 m12 l4">
			<div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>Productividad</strong></h4>
		        	<div class="texto-card-sevices">
		        		En em-conecta nos preocupamos por la utilizacion del timepo
		        		por esta razon implementamos un servicio que te permite conectar los datos de tu
		        		sitio a nosotros con un solo clik
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-merge_type icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>WS SOAP REST</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>Marketing</strong></h4>
		        	<div class="texto-card-sevices">
		        		Presenta la oferta de tu firma, difunde información precisa y constituye una herramienta comercial de marketing muy valiosa para aumentar tus ventas
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-library_books icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>PORTAFOLIO</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        <h4 class="center-align teal-text text-darken-4"><strong>Datos</strong></h4>
		        	<div class="texto-card-sevices">
		        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-database icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
		      </div>
		    </div>
	    </div>
	</article>
</section>