<section class="section-card">
	<div class="white-text teal darken-4 carta-principal z-depth-2">
		<article>
        	<div class="texto-card-sevices">
        		<?php echo $this->configuracion['otros_conecta_al_mundo']; ?>
        	</div>
        	<div class="radio-icon">
        		<div class="radio-div white black-text">
        			<span class="icon-power-plug icon-logo-unete"></span>
        		</div>
        	</div>
	    	<div class="card-content">
	    		<div class="card-title activator blue-text text-darken-1 center-align"><strong>Conecta al mundo</strong></div>
	    	</div>
        </article>
	</div>
</section>
<section>
	<h3 class="center-align">Efectividad</h3>
</section>
<section class="text-info-publica">
	<p class="container">
		<?php echo $this->configuracion['otros_efectividad']; ?>
	</p>
</section>
<div class="parallax-container margin-paralax">
    <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/person-apple-laptop-notebook.jpg"></div>
</div>
<section>
	<h3 class="center-align">Servicios</h3>
</section>
<section class="text-info-publica">
	<article class="container row">
		<div class="col s12 m12 l4">
			<div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>Productividad</strong></h4>
		        	<div class="texto-card-sevices">
		        		<?php echo $this->configuracion['otros_productividad']; ?>
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-merge_type icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>WS SOAP REST</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>Marketing</strong></h4>
		        	<div class="texto-card-sevices">
		        		<?php echo $this->configuracion['otros_marketing']; ?>
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-library_books icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>PORTAFOLIO</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        <h4 class="center-align teal-text text-darken-4"><strong>Datos</strong></h4>
		        	<div class="texto-card-sevices">
		        		<?php echo $this->configuracion['otros_datos']; ?>
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-database icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
		      </div>
		    </div>
	    </div>
	</article>
</section>