<div class="parallax-container">
  	<div class="parallax"><img src="<?php echo BASE_URL ?>/public/img/hands-people-woman-working.jpg"></div>
</div>
<div class="row container form-contact">
    <div class="col s12 m12 l12">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Contactanos</strong></h4>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-database icon-logo-unete"></span>
	        		</div>
	        	</div>
	        	<div class="texto-card-sevices">
				  <div class="row">
				    <form class="col s12">
				    <div class="row">
				        <div class="input-field col s12 m6 l6">
				          <input id="first_name" type="text" class="validate">
				          <label for="first_name">Nombre</label>
				        </div>
				        <div class="input-field col s12 m6 l6">
				          <input id="last_name" type="text" class="validate">
				          <label for="last_name">Apellido</label>
				        </div>
				      	<div class="input-field col s12 m6 l6">
				        	<input id="asunto" type="text" class="validate">
				        	<label for="asunto">Asunto</label>
				      	</div>
				      	<div class="input-field col s12 m6 l6">
				        	<input id="email" type="email" class="validate">
				        	<label for="email">Email</label>
				      	</div>
				    </div>
				      <div class="row">
				        <div class="input-field col s12">
				          	<textarea id="textarea1" class="materialize-textarea"></textarea>
          					<label for="textarea1">Mensaje</label>
				        </div>
				      </div>
					  <button class="btn waves-effect transparent btn-contacto" type="submit" name="action">Enviar</button>
				    </form>
				  </div>
	        	</div>
	        </article>
	      </div>
	    </div>
    </div>
</div>