<div class="content-image ">
	<img class="img-planes" src="<?php echo BASE_URL ?>public/img/pexels-photo-38198.jpeg">
	<h4 class="white-text absulut-title">
		!Conectate con el mundo¡
	</h4>
</div>
<h3 class="relative-title">
	Planes
</h3>
<section class="text-info-publica">
	<article class="container row">
		<div class="col s12 m12 l4">
			<div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>Basico</strong></h4>
		        	<div class="texto-card-sevices">
		        		En em-conecta nos preocupamos por la utilizacion del timepo
		        		por esta razon implementamos un servicio que te permite conectar los datos de tu
		        		sitio a nosotros con un solo clik
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-merge_type icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>WS SOAP REST</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        	<h4 class="center-align teal-text text-darken-4"><strong>General</strong></h4>
		        	<div class="texto-card-sevices">
		        		Presenta la oferta de tu firma, difunde información precisa y constituye una herramienta comercial de marketing muy valiosa para aumentar tus ventas
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-library_books icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>PORTAFOLIO</strong></div>
		      </div>
		    </div>
	    </div>
	    <div class="col s12 m12 l4">
		    <div class="card">
		      <div class="card-image waves-effect waves-block waves-light">
		        <article>
		        <h4 class="center-align teal-text text-darken-4"><strong>Optimo</strong></h4>
		        	<div class="texto-card-sevices">
		        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
		        	</div>
		        	<div class="radio-icon">
		        		<div class="radio-div">
		        			<span class="icon-database icon-logo-unete"></span>
		        		</div>
		        	</div>
		        </article>
		      </div>
		      <div class="card-content">
		        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
		      </div>
		    </div>
	    </div>
	</article>
</section>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/apple-iphone-books-desk.jpg"></div>
</div>
<div class="row container">
    <div class="col s12 m12 l12">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Beneficios</strong></h4>
	        	<div class="texto-card-sevices">
	        		Genera graficos, reportes, facturas para tu empresa, analiza los datos de tu empresa toma desiciones acertadas y dale el giro que le hace falta para ser exitoso.
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-database icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	      <div class="card-content">
	        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong>REPORTES GRAFICOS</strong></div>
	      </div>
	    </div>
    </div>
</div>