<div class="content-image ">
	<img class="img-planes" src="<?php echo BASE_URL ?>public/img/pexels-photo-38198.jpeg">
	<h4 class="white-text absulut-title">
		!Conectate con el mundo¡
	</h4>
</div>
<h3 class="relative-title">
	Planes
</h3>
<section class="text-info-publica">
	<article class="container row">
		<?php $varcount = count($this->configuracion); 
			$array_icons = array('device_hub', 'details', 'filter_tilt_shift');
		?>

		<?php for ($i=0; $i < $varcount ; $i++) { ?>
			<div class="col s12 m12 l4">
				<div class="card">
			      <div class="card-image waves-effect waves-block waves-light">
			        <article>
			        	<h4 class="center-align teal-text text-darken-4"><strong><?php echo $this->configuracion[$i]['planes_titulo']; ?></strong></h4>
			        	<div class="texto-card-sevices">
			        		<?php echo $this->configuracion[$i]['contenido']; ?>
			        	</div>
			        	<div class="radio-icon">
			        		<div class="radio-div">
			        			<span class="<?php echo 'icon-'.$array_icons[$i];?> icon-logo-unete"></span>
			        		</div>
			        	</div>
			        </article>
			      </div>
			      <div class="card-content">
			        <div class="card-title activator blue-text text-darken-1 center-align title-font-bot"><strong><?php echo $this->configuracion[$i]['planes_title_inf']; ?></strong></div>
			      </div>
			    </div>
		    </div>
		<?php } ?>
	</article>
</section>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/apple-iphone-books-desk.jpg"></div>
</div>
<div class="row container">
    <div class="col s12 m12 l12">
	    <div class="card">
	      <div class="card-image waves-effect waves-block waves-light">
	        <article>
	        <h4 class="center-align teal-text text-darken-4"><strong>Beneficios</strong></h4>
	        	<div class="texto-card-sevices">
	        		<?php for ($w=0; $w < count($this->configuracion); $w++) { ?>
	        			<strong><?php echo $this->configuracion[$w]['planes_titulo']?></strong>:
	        			<?php for ($x=0; $x < count($this->beneficios); $x++) { ?>
	        				<?php
	        				 	if ($this->configuracion[$w]['idplanes'] == $this->beneficios[$x]['planes_idplanes']) {
	        						echo $this->beneficios[$x]['beneficios_lista_beneficios'];
	        				 	} 
	        				?>
	        			<?php } ?><br>
	        		<?php }	?>
	        	</div>
	        	<div class="radio-icon">
	        		<div class="radio-div">
	        			<span class="icon-verified_user icon-logo-unete"></span>
	        		</div>
	        	</div>
	        </article>
	      </div>
	    </div>
    </div>
</div>