<div class="row center-align">
	<div class="col s12 m12 l12 padding-menu-search grey-text darken-2">
		<div class="row">
			<div class="col s1 m1 l1">
				<h5 data-activates="slide-out" class="button-collapse show-on-large icon-menu"></h5>
			</div>
			<div class="col s4 l4 m4">
				<nav class="white">
				    <div class="nav-wrapper">
				      <form>
				        <div class="input-field">
				          <input id="search" type="search" required placeholder="Buscar">
				          <label for="search"><span class="icon-search"></span></label>
				        </div>
				      </form>
				    </div>
				</nav>
			</div>
			<div class="col s1 m1 l1">
				<h5 class="icon-drive"></h5>
			</div>
			<div class="col s1 m1 l1">
				<h5 class="icon-markunread"></h5>
			</div>
			<div class="col s1 m1 l1">
				<h5 class="icon-notifications"></h5>
			</div>
			<div class="col s4 m4 l4 row">
				<div class="img-container col s4 m4 l4">
					<img class="radio-img" src="<?php echo BASE_URL?>public/img/portafolio/girl-pretty-beautiful-young-47215-compressor.jpeg">
				</div>
				<div class="menu-container col s8 m8 l8">
					<h5 class='dropdown-button' href='#' data-activates='dropdown1'>nombre de usuario<span class="icon-arrow_drop_down"></span></h5>

					<!-- Dropdown Structure -->
					<ul id='dropdown1' class='dropdown-content'>
					    <li><a href="#!">one</a></li>
					    <li class="divider"></li>
					    <li><a href="#!">two</a></li>
					    <li class="divider"></li>
					    <li><a href="#!">three</a></li>
					</ul>
					<!-- Dropdown Trigger -->
				</div>
			</div>
		</div>
	</div>
	<div class="cards_container row">

		<div class="col s12 m3 card_mail">
	        <div class="card white card_titles">
	            <div class="card-mail col s12 white-text">Mensajes</div>
	        </div>
        </div>

        <div class="col s12 m9 card_mail">
	        <div class="card white card_titles">
	        	<div class="card-mail left-align col s12 white-text">Mensaje</div>
	        </div>
        </div>

        <div class="col s12 m3">
	        <div class="card white my_card card_mail">
	        <?php for ($i=0; $i < count( $this->mensaje ); $i++) { ?>
	        	<div class="card-content black-text">
	              <div class="card-name col s12 user_name"> <?php echo ucwords($this->mensaje[$i]['mensaje_nombre']).' '.ucwords($this->mensaje[$i]['mensaje_apellido']); ?></div>
	              <div class="col s3">
	              	<div class="radio-img-name <?php echo substr(lcfirst($this->mensaje[$i]['mensaje_nombre']), 0, 1); ?> white-text"><?php echo substr(ucfirst($this->mensaje[$i]['mensaje_nombre']), 0, 1); ?></div>
	              </div>
	              <p class="col s9 truncate">
	              	<?php echo ucfirst($this->mensaje[$i]['mensaje_asunto']); ?>
	              </p>
	            </div>
	        <?php } ?>
	        </div>
        </div>


        <div class="col s12 m9">
	        <div class="card white my_card card_mail">
	            <div class="card-content black-text">
	              <div class="card-name user-card left-align col s12"><?php echo ucwords($this->mensaje[0]['mensaje_nombre']).' '.ucwords($this->mensaje[0]['mensaje_apellido']); ?></div>
	              <div class="col s1">
	              	<div class="radio-img-name-msn <?php echo substr(lcfirst($this->mensaje[0]['mensaje_nombre']), 0, 1); ?>  white-text"><?php echo substr(ucfirst($this->mensaje[0]['mensaje_nombre']), 0, 1); ?></div>
	              </div>
	              <div class="col s11 right-align"><?php echo ucfirst($this->mensaje[0]['mensaje_asunto']); ?></div>
	              <div class="col s11 right-align"><?php echo ucfirst($this->mensaje[0]['mensaje_email']); ?></div>

	              <div class="msn-card col s12 left-align">
	              	<?php echo ucfirst($this->mensaje[0]['mensaje_mensaje']); ?>
	              </div>
	            </div>
	        </div>
        </div>

        <div class="row">
	        <div class="col s12 m6">
	          <div class="card white user_card">
	            <div class="card-content">
		            <div class="img-container-perfil">
						<img class="radio-img-perfil" src="<?php echo BASE_URL?>public/img/portafolio/girl-pretty-beautiful-young-47215-compressor.jpeg">
					</div>
					<div class="option_editar"><a href="#">Editar foto</a></div>
		            <div class="card-title black-text padding-perfil"><strong><?php echo 'Hola! '.$_SESSION['usuario'] ?></strong></div>
		            <p class="col s12 black-text padding-perfil">Bienvenido a micolombiaenlinea este es tu perfil, modifica todo lo que tú quieras.</p>
		            <div class="col s6 left-align padding-perfil">
		            	<?php echo $_SESSION['nombre'].' '.$_SESSION['apellido'] ?>
		            </div>
		            <div class="col s6 right-align padding-perfil">
		            	<a href="#">Editar nombres</a>
		            </div>
		            <div class="col s6 left-align padding-perfil">
		            	<?php echo $_SESSION['usuario']?>
		            </div>
		            <div class="col s6 right-align padding-perfil">
		            	<a href="#">Editar usuario</a>
		            </div>
		            <div class="col s6 left-align padding-perfil">
		            	<?php echo '**************'?>
		            </div>
		            <div class="col s6 right-align padding-perfil">
		            	<a href="#">Editar contraseña</a>
		            </div>
	            </div>
	          </div>
	        </div>
	    </div>

	</div>
</div>