<div class="container-dashboard">
	<div class="row padding_cards">
	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card">
		 		<div class="card_title">
		 			Correo <span class="icon-mail_outline"></span>
		 		</div>
		 		<div class="container_info">
		 			<ul>
		 				<li>
		 					ya esta el correo
		 				</li>
		 				<li>
		 					ya esta el correo
		 				</li>
		 			</ul>
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card">
		 		<div class="card_title">
		 			Usuarios <span class="icon-user"></span>
		 		</div>
		 		<div class="container_info">
		 			contenido de la tarjeta
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card">
		 		<div class="card_title">
		 			Redes sociales <span class="icon-flow-tree"></span>
		 		</div>
		 		<div class="container_info">
		 			contenido de la tarjeta
		 		</div>
	 		</div>
	 	</div>
    </div>
</div>