<div class="fixed-action-btn vertical" style="bottom: 45px; left: 24px;">
    <a class="btn-floating btn-large white">
      <i class="black-text large mdi-navigation-menu"></i>
    </a>
    <ul class="navigation_menu_vertical">
      <li id="mail"><a class="btn-floating white"><i class="black-text icon-mail5"></i></a> <div class="btn-floating set_icon">Mail</div></li>
      <li id="blog"><a class="btn-floating white"><i class="black-text icon-blog"></i></a> <div class="btn-floating set_icon">Blog</div></li>
      <li id="tienda"><a class="btn-floating white "><i class="black-text icon-store_mall_directory"></i></a><div class="btn-floating set_icon">Tienda</div></li>
      <li id="portafolio"><a class="btn-floating white "><i class="black-text icon-suitcase"></i></a><div class="btn-floating set_icon">Portafolio</div></li>
      <li id="conf_inicial"><a class="btn-floating white "><i class="black-text icon-publish"></i></a><div class="btn-floating set_icon">Confi inicial</div></li>
    </ul>
</div>

<div class="container-dashboard">
	<div class="row padding_cards">

	 	<div class="card_container  col s12 m12 l12">

	 		<div class="my_card card_mail">
		 		<div class="card_title">
		 			Correo <span class="icon-mail_outline"></span>
		 		</div>
		 		<div class="container_info mail_email">
			 		<ul class="collapsible popout" data-collapsible="accordion">
						<?php for ($i=0; $i < count( $this->mensaje ); $i++) { ?>
						    <li>
						      <div class="collapsible-header white"><span class="left"><strong><?php echo ucwords($this->mensaje[$i]['mensaje_nombre']).' '.ucwords($this->mensaje[$i]['mensaje_apellido']); ?></strong></span><span class="right hide-on-med-and-down"><strong><?php echo ucfirst($this->mensaje[$i]['mensaje_asunto']); ?></strong></span></div>
						      <div class="collapsible-body white">
						      		<h4 class="padding_titles">
						      			<?php echo ucfirst($this->mensaje[$i]['mensaje_asunto']); ?>
						      		</h4>
						      		<h5 class="padding_titles">
						      			<?php echo ucwords($this->mensaje[$i]['mensaje_nombre']).' '.ucwords($this->mensaje[$i]['mensaje_apellido']); ?><br>
						      			<h6 class="padding_titles"><?php echo ucfirst($this->mensaje[$i]['mensaje_email']); ?></h6>
						      		</h5>
								     <p>
								     	<?php echo ucfirst($this->mensaje[$i]['mensaje_mensaje']); ?>
								     </p>
						      </div>
						    </li>
						<?php } ?>
					</ul>
		 		</div>
	 		</div>
	 		
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Usuarios <span class="icon-user"></span>
		 		</div>
		 		<div class="container_info">
		 			
				  <div class="row">
				    <div class="col s12">
				      <ul class="tabs">
				        <li class="tab col s3"><a href="#test1">Lista</a></li>
				        <li class="tab col s3"><a href="#test2">Nuevo</a></li>
				        <li class="tab col s3"><a href="#test3">Editar</a></li>
				      </ul>
				    </div>
				    <div id="test1" class="col s12">
				    	<div class="container_info">
			 		
							<div class="collection">
							<?php for ($i=0; $i < count($this->usuarios); $i++) { ?>
								<a href="#!" class="collection-item"><?php echo ucwords($this->usuarios[$i]['usuario_nombre'].' '.$this->usuarios[$i]['usuario_apellido']) ?><span class="<?php if ($this->usuarios[$i]['usuario_activate'] == 1){echo "badge";}else{echo "new badge";} ?> "><?php if ($this->usuarios[$i]['usuario_activate'] == 1){echo "Activado";}else{ echo 'Activar';} ?></span></a>
							<?php } ?>
							</div>
			            
					 	</div>
				    </div>
				    <div id="test2" class="col s12">
				    	<div class="card_nuevo">
				    		<div class="userform">
							    <form id="form_nuevo_usuario" class="col s12">
							      <div class="row">
							      	<div class="input-field col s12">
							          <i class="icon_dashboard icon-user2 prefix"></i>
							          <input id="icon_prefix" type="text" class="validate" name="nombre">
							          <label for="icon_prefix">Nombre</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-user2 prefix"></i>
							          <input id="icon_prefix" type="text" class="validate" name="apellido">
							          <label for="icon_prefix">Apellido</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-account_circle prefix"></i>
							          <input id="icon_prefix" type="text" class="validate" name="usuario">
							          <label for="icon_prefix">Nombre de usuario</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate" name="pass">
							          <label for="icon_telephone">Contraseña</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate" name="validar_pass">
							          <label for="icon_telephone">Validar contraseña</label>
							        </div>
							      </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">Guardar</button>
							    </form>
							</div>
				    	</div>
				    </div>
				    <div id="test3" class="col s12">
				    	<div class="card_nuevo">
				    		<div class="userform">
							    <form id="form_editar_usuario" class="col s12">
							    	<input type="hidden" name="idusuario"  value="<?php echo $_SESSION['idusuario']; ?>">
							      <div class="row">
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-account_circle prefix"></i>
							          <input name="usuario" id="icon_prefix" type="text" class="validate" value="<?php echo $_SESSION['usuario'] ?>">
							          <label for="icon_prefix">Nombre de usuario</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input name="pass" id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Contraseña</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input name="validar_pass" id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Validar contraseña</label>
							        </div>
							      </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">editar</button>
							    </form>
							</div>
				    	</div>
				    </div>
				  </div>
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Redes sociales <span class="icon-flow-tree"></span>
		 		</div>
		 		<div class="container_info">

		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#ulr_nuevo">Nuevo</a></li>
					      </ul>
					    </div>
					    <div id="ulr_nuevo" class="col s12">
				 			<div class="row">
							    <form id="nueva_red_social" class="col s12">
							      <div class="row">
							        <div class="input-field col s12">
								    <select name="nuevo_red_social">
									      <option value="" disabled selected>Seleccione un red</option>
									      <?php for ($i=0; $i < count($this->redsocial); $i++) { ?>
									      	<option value="<?php echo $this->redsocial[$i]['idsocial'] ?>"><?php echo $this->redsocial[$i]['social_nombre']; ?></option>
									      <?php } ?>
									</select>
									</div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-http prefix"></i>
							          <input placeholder="debe contener http://" id="icon_telephone" type="url" class="validate" name="url_redsocial">
							          <label for="icon_telephone">Url red social</label>
							        </div>
							      </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">Guardar</button>
							    </form>
							</div>
					    </div>
					</div>
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Favi Icon <span class="icon-http"></span>
		 		</div>
			    <form id="form_favi_icon" class="col s12">
			        <div class="file-field input-field">
				      <div class="btn">
				        <span>Archivo</span>
				        <input name="img_favi_icon" type="file" multiple>
				      </div>
				      <div class="file-path-wrapper">
				        <input class="file-path validate" type="text" placeholder="Icono empresa">
				      </div>
				    </div>
				</form>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m12 l12">
	 		<div class="my_card portafolio_card">
		 		<div class="card_title">
		 			Portafolio <span class="icon-flow-tree"></span>
		 			<div id="respuesta">
		 				<?php 
		 				if (isset($this->portafolio[0]['portafolio_logo_name'])) {
		 					if ($this->portafolio[0]['portafolio_logo_name'] != '') {?>
		 						<div class="logo"><img class="img-logo" src="<?php echo BASE_URL.'public/img/carpeta/'.$this->portafolio[0]['portafolio_logo_name'] ?>"></div>
		 					<?php }
		 				}?>
		 			</div>
		 		</div>
		 		<div class="container_info">
		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3 <?php if(count($this->portafolio) != 0){echo 'disabled';}else{echo '';} ?>"><a href="#nuevo_portafolio">Nuevo</a></li>
					        <li class="tab col s3 <?php if(count($this->portafolio) == 0){echo 'disabled';}else{echo '';} ?>"><a class="<?php if(count($this->portafolio) != 0){echo 'active';}else{echo '';} ?>" href="#editar_portafolio">Editar</a></li>
					      </ul>
					    </div>
					    <div id="nuevo_portafolio" class="col s12">
					    	<div class="row">
							    <form id="form_portafolio" class="col s12" enctype="multipart/form-data">
							        <div class="file-field input-field">
								      <div class="btn">
								        <span>Archivo</span>
								        <input name="img_Logo" type="file" multiple>
								      </div>
								      <div id="input_new_file_name" class="file-path-wrapper">
								        <input name="nombre_logo" class="file-path validate" type="text" placeholder="El logo debe aproximarse a ser cuadrado">
								      </div>
								    </div>
							      	<div class="row">
								        <div class="input-field col s12">
								          <input id="icon_prefix" type="text" class="validate" name="telefono">
								          <label for="icon_prefix">Telefonos</label>
								        </div>
							        </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <input id="icon_prefix" type="text" class="validate" name="direccion">
								          <label for="icon_prefix">Direccion</label>
								        </div>
							        </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="bienvenido"></textarea>
								          <label for="icon_prefix2">Bienvenido</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="innovacion"></textarea>
								          <label for="icon_prefix2">Innovacion</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="integracion"></textarea>
								          <label for="icon_prefix2">Integracion</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="integridad"></textarea>
								          <label for="icon_prefix2">Integridad</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="historia"></textarea>
								          <label for="icon_prefix2">Historia</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="mision"></textarea>
								          <label for="icon_prefix2">Mision</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="vision"></textarea>
								          <label for="icon_prefix2">Vision</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="marca"></textarea>
								          <label for="icon_prefix2">Marca</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="trabajo"></textarea>
								          <label for="icon_prefix2">Como trabajamos</label>
								        </div>
								    </div>
								    <button class="col s12 btn waves-effect black-text white" type="submit">Guardar</button>
							    </form>
							</div>
					    </div>
					    <div id="editar_portafolio" class="col s12">
					    	<div class="row">
							    <form id="editar_form_portafolio" class="col s12" enctype="multipart/form-data">
							    	<input name="portafolio_name" type="hidden" value="<?php echo $this->portafolio[0]['idportafolio']; ?>">
							        <div class="file-field input-field">
								      <div class="btn">
								        <span>Archivo</span>
								        <input name="editar_img_Logo" type="file" multiple>
								      </div>
								      <div id="edtar_input_new_file_name" class="file-path-wrapper">
								        <input name="editar_nombre_logo" class="file-path validate" type="text" value="<?php echo $this->portafolio[0]['portafolio_logo_name'] ?>" placeholder="El logo debe aproximarse a ser cuadrado">
								      </div>
								    </div>
							      	<div class="row">
								        <div class="input-field col s12">
								          <input id="icon_prefix" type="text" class="validate" name="editar_telefono" value="<?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_telefonos'];} ?>">
								          <label for="icon_prefix">Telefonos</label>
								        </div>
							        </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <input id="icon_prefix" type="text" class="validate" name="editar_direccion" value="<?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_direccion']; }?>">
								          <label for="icon_prefix">Direccion</label>
								        </div>
							        </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_bienvenido"><?php if(count($this->portafolio) == 0){echo "";}else{ echo $this->portafolio[0]['portafolio_bienvenido'];}?></textarea>
								          <label for="icon_prefix2">Bienvenido</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_innovacion" ><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_innovacion'];}?></textarea>
								          <label for="icon_prefix2">Innovacion</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_integracion"><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_integracion'];}?></textarea>
								          <label for="icon_prefix2">Integracion</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_integridad"><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_integridad'];}?></textarea>
								          <label for="icon_prefix2">Integridad</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_historia" ><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_historia_cultura'];}?></textarea>
								          <label for="icon_prefix2">Historia</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_mision" ><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_mision'];}?></textarea>
								          <label for="icon_prefix2">Mision</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_vision" ><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_vision'];}?></textarea>
								          <label for="icon_prefix2">Vision</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_marca"><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_marca'];}?></textarea>
								          <label for="icon_prefix2">Marca</label>
								        </div>
								    </div>
							        <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea" name="editar_trabajo"><?php if(count($this->portafolio) == 0){echo "";}else{echo $this->portafolio[0]['portafolio_como_trabajamos'];}?></textarea>
								          <label for="icon_prefix2">Como trabajamos</label>
								        </div>
								    </div>
								    <button class="col s12 btn waves-effect black-text white" type="submit">Editar</button>
							    </form>
							</div>
					    </div>
					</div>		 			
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card productos_cad">
		 		<div class="card_title">
		 			Tipo de producto <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">

		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#tipo_nuevo">Nuevo</a></li>
					        <li class="tab col s3"><a href="#tipo_editar">Editar</a></li>
					        <li class="tab col s3"><a href="#tipo_eliminar">Eliminar</a></li>
					      </ul>
					    </div>
					    <div id="tipo_nuevo" class="col s12">
					    	<div class="row">
							    <form id="form_tipo_producto" class="col s12">
							      <div class="row">
							        <div class="input-field col s12">
							          <input name="name_tipo_poducto" id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Tipos de producto</label>
							        </div>
							      </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">guardar</button>
							    </form>
							</div>
					    </div>
					    <div id="tipo_editar" class="col s12">
					    	<div class="row">
							    <form id="form_editar_tipo" class="col s12">
							      <div class="input-field col s12">
								    <select name="select_tipo_producto">
								      <option value="" disabled selected>Seleccione un tipo</option>
								      <?php for ($a=0; $a < count($this->tiposproductos); $a++) { ?>
								      		<option value="<?php echo $this->tiposproductos[$a]['idproductos_tipo'] ?>"><?php echo $this->tiposproductos[$a]['productos_tipo_nombre'] ?></option>
								      <?php } ?>
								    </select>
								  </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input name="editar_name_tipo_producto" id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Tipos de producto</label>
							        </div>
							      </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">Editar</button>
							    </form>
							</div>
					    </div>
					    <div id="tipo_eliminar" class="col s12">
					    	<div class="row">
							    <form id="form_eliminar_tipo" class="col s12">
							      <div class="input-field col s12">
								    <select name="select_delete_tipo_producto">
								      <option value="" disabled selected>Seleccione un tipo</option>
								      <?php for ($a=0; $a < count($this->tiposproductos); $a++) { ?>
								      		<option value="<?php echo $this->tiposproductos[$a]['idproductos_tipo'] ?>"><?php echo $this->tiposproductos[$a]['productos_tipo_nombre'] ?></option>
								      <?php } ?>
								    </select>
								  </div>
							      <button class="col s12 btn waves-effect black-text white" type="submit">eliminar</button>
							    </form>
							</div>
					    </div>
					</div>		 			
		 		</div>
		 	</div>
		</div>

		<div class="card_container col s12 m6 l4">
	 		<div class="my_card productos_cad">
		 		<div class="card_title">
		 			Producto <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">

		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#producto_nuevo">Nuevo</a></li>
					        <li class="tab col s3"><a href="#producto_editar">Editar</a></li>
					        <li class="tab col s3"><a href="#producto_eliminar">Eliminar</a></li>
					      </ul>
					    </div>
					    <div id="producto_nuevo" class="col s12">
							<div class="row">
							    <form id="form_nuevo_producto" class="col s12">
							      <div class="input-field col s12">
								    <select name="producto_select_tipo_producto">
								      <option value="" disabled selected>Seleccione un tipo</option>
								      <?php for ($a=0; $a < count($this->tiposproductos); $a++) { ?>
								      		<option value="<?php echo $this->tiposproductos[$a]['idproductos_tipo'] ?>"><?php echo $this->tiposproductos[$a]['productos_tipo_nombre'] ?></option>
								      <?php } ?>
								    </select>
								  </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input name="producto_nombre_producto" id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Normbre del producto</label>
							        </div>
							      </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input name="producto_valor_producto" id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Valor del producto</label>
							        </div>
							      </div>
							      <div class="row">
								        <div class="input-field col s12">
								          <textarea name="producto_descripcion_producto" id="icon_prefix2" class="materialize-textarea"></textarea>
								          <label for="icon_prefix2">Descripcion</label>
								        </div>
								  </div>
								  <button class="col s12 btn waves-effect black-text white" type="submit">guardar</button>
							    </form>
							</div>
					    </div>
					    <div id="producto_editar" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un producto</option>
								      <?php for ($b=0; $b < count($this->productos); $b++) { ?>
								      		<option value="<?php echo $this->productos[$b]['idproducto']; ?>"><?php echo $this->productos[$b]['producto_nombre']; ?></option>
								      <?php } ?>
								    </select>
								  </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Normbre del producto</label>
							        </div>
							      </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Valor del producto</label>
							        </div>
							      </div>
							      <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
								          <label for="icon_prefix2">Descripcion</label>
								        </div>
								  </div>
							    </form>
							</div>
					    </div>
					    <div id="producto_eliminar" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un tipo</option>
								      <option value="1">Option 1</option>
								      <option value="2">Option 2</option>
								      <option value="3">Option 3</option>
								    </select>
								  </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Normbre del producto</label>
							        </div>
							      </div>
							      <div class="row">
							        <div class="input-field col s12">
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Valor del producto</label>
							        </div>
							      </div>
							      <div class="row">
								        <div class="input-field col s12">
								          <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
								          <label for="icon_prefix2">Descripcion</label>
								        </div>
								  </div>
							    </form>
							</div>
					    </div>
					</div>		 			
		 		</div>
		 	</div>
		</div>

		<div class="card_container col s12 m6 l4">
	 		<div class="my_card productos_cad">
		 		<div class="card_title">
		 			Tags <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">
		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#tag_nuevo">Nuevo</a></li>
					        <li class="tab col s3"><a href="#tag_editar">Editar</a></li>
					      </ul>
					    </div>
					    <div id="tag_nuevo" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un producto</option>
								      <option value="1">Option 1</option>
								      <option value="2">Option 2</option>
								      <option value="3">Option 3</option>
								    </select>
								  </div>
							      <div class="row">
								        <div class="input-field col s12">
								          <textarea placeholder="palabras frases separadas por comas" id="icon_prefix2" class="materialize-textarea"></textarea>
								          <label for="icon_prefix2">Tangs</label>
								        </div>
								  </div>
							    </form>
							</div>
					    </div>
					    <div id="tag_editar" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un producto</option>
								      <option value="1">Option 1</option>
								      <option value="2">Option 2</option>
								      <option value="3">Option 3</option>
								    </select>
								  </div>
							      <div class="row">
								        <div class="input-field col s12">
								          <textarea placeholder="palabras frases separadas por comas" id="icon_prefix2" class="materialize-textarea"></textarea>
								          <label for="icon_prefix2">Tangs</label>
								        </div>
								  </div>
							    </form>
							</div>
					    </div>
					</div>
        
		 			
		 		</div>
		 	</div>
		</div>

		<div class="card_container col s12 m6 l4">
	 		<div class="my_card productos_cad">
		 		<div class="card_title">
		 			Fotos <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">
		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#foto_nuevo">Nueva foto</a></li>
					        <li class="tab col s3"><a href="#foto_dos">Editar foto</a></li>
					      </ul>
					    </div>
					    <div id="foto_nuevo" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="file-field input-field">
								      <div class="btn">
								        <span>Archivo</span>
								        <input type="file" multiple>
								      </div>
								      <div class="file-path-wrapper">
								        <input class="file-path validate" type="text" placeholder="Foto producto">
								      </div>
								  </div>
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un producto</option>
								      <option value="1">Option 1</option>
								      <option value="2">Option 2</option>
								      <option value="3">Option 3</option>
								    </select>
								  </div>
							    </form>
							</div>
					    </div>
					    <div id="foto_dos" class="col s12">
					    	<div class="row">
							    <form class="col s12">
							      <div class="file-field input-field">
								      <div class="btn">
								        <span>Archivo</span>
								        <input type="file" multiple>
								      </div>
								      <div class="file-path-wrapper">
								        <input class="file-path validate" type="text" placeholder="Foto producto">
								      </div>
								  </div>
							      <div class="input-field col s12">
								    <select>
								      <option value="" disabled selected>Seleccione un producto</option>
								      <option value="1">Option 1</option>
								      <option value="2">Option 2</option>
								      <option value="3">Option 3</option>
								    </select>
								  </div>
							    </form>
							</div>
					    </div>
					</div>
        
		 			
		 		</div>
		 	</div>
		</div>

		<div class="card_container col s12 m6 l6">
	 		<div class="my_card blog_cad">
		 		<div class="card_title">
		 			Blog <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">
		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#blog_nuevo">Nuevo</a></li>
					        <li class="tab col s3"><a href="#blog_editar">Editar</a></li>
					        <li class="tab col s3"><a href="#blog_asociar">Asociar</a></li>
					        <li class="tab col s3"><a href="#blog_eliminar">Eliminar</a></li>
					      </ul>
					    </div>
					    <div id="blog_nuevo" class="col s12">

					      	<div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Titulo</label>
						        </div>
					        </div>
					        <div class="row">
						        <div class="input-field col s12">
						          <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
						          <label for="icon_prefix2">Contenido</label>
						        </div>
						  	</div>
						  	<div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Autor</label>
						        </div>
					        </div>
					        <div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Tema</label>
						        </div>
					        </div>

					    </div>

					    <div id="blog_editar" class="col s12">
					    	<div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Titulo</label>
						        </div>
					        </div>
					        <div class="row">
						        <div class="input-field col s12">
						          <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
						          <label for="icon_prefix2">Contenido</label>
						        </div>
						  	</div>
						  	<div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Autor</label>
						        </div>
					        </div>
					        <div class="row">
						        <div class="input-field col s12">
						          <input id="icon_prefix" type="text" class="validate">
						          <label for="icon_prefix">Tema</label>
						        </div>
					        </div>
					    </div>

					    <div id="blog_asociar" class="col s12">
					    	<div class="input-field col s12">
							    <select>
							      <option value="" disabled selected>Seleccione un producto</option>
							      <option value="1">Option 1</option>
							      <option value="2">Option 2</option>
							      <option value="3">Option 3</option>
							    </select>
							</div>
							<div class="input-field col s12">
							    <select>
							      <option value="" disabled selected>Seleccione un producto</option>
							      <option value="1">Option 1</option>
							      <option value="2">Option 2</option>
							      <option value="3">Option 3</option>
							    </select>
							</div>
					    </div>

					    <div id="blog_eliminar" class="col s12">
					    	<div class="input-field col s12">
							    <select>
							      <option value="" disabled selected>Seleccione un producto</option>
							      <option value="1">Option 1</option>
							      <option value="2">Option 2</option>
							      <option value="3">Option 3</option>
							    </select>
							</div>
					    </div>
					</div>
        
		 		</div>
		 	</div>
		</div>

		<div class="card_container col s12 m6 l6">
	 		<div class="my_card blog_cad">
		 		<div class="card_title">
		 			Fotos Blog <span class="icon-flow-tree"></span>
		 		</div>

		 		<div class="container_info">

		 			<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a href="#nuevo_blog_foto">Nuevo</a></li>
					        <li class="tab col s3"><a href="#editar_blog_foto">Editar</a></li>
					      </ul>
					    </div>
					    <div id="nuevo_blog_foto" class="col s12">
					    	<div class="file-field input-field">
						      <div class="btn">
						        <span>Archivo</span>
						        <input type="file" multiple>
						      </div>
						      <div class="file-path-wrapper">
						        <input class="file-path validate" type="text" placeholder="Foto blog">
						      </div>
						    </div>
						    <div class="input-field col s12">
							    <select>
							      <option value="" disabled selected>Seleccione un articulo</option>
							      <option value="1">Option 1</option>
							      <option value="2">Option 2</option>
							      <option value="3">Option 3</option>
							    </select>
							</div>
					    </div>
					    <div id="editar_blog_foto" class="col s12">
					    	<div class="file-field input-field">
						      <div class="btn">
						        <span>Archivo</span>
						        <input type="file" multiple>
						      </div>
						      <div class="file-path-wrapper">
						        <input class="file-path validate" type="text" placeholder="Foto blog">
						      </div>
						    </div>
						    <div class="input-field col s12">
							    <select>
							      <option value="" disabled selected>Seleccione un articulo</option>
							      <option value="1">Option 1</option>
							      <option value="2">Option 2</option>
							      <option value="3">Option 3</option>
							    </select>
							</div>
					    </div>
					</div>
        
		 			
		 		</div>
		 	</div>
		</div>
    </div>
</div>