<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; left: 24px;">
    <a class="btn-floating btn-large white">
      <i class="black-text large mdi-navigation-menu"></i>
    </a>
    <ul class="navigation_menu_vertical">
      <li><a class="btn-floating white "><i class="icon-insert_chart"></i></a></li>
      <li><a class="btn-floating white  darken-1"><i class="icon-format_quote"></i></a></li>
      <li><a class="btn-floating white "><i class="icon-publish"></i></a></li>
      <li><a class="btn-floating white "><i class="icon-attach_file"></i></a></li>
    </ul>
</div>

<div class="container-dashboard">
	<div class="row padding_cards">
	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Correo <span class="icon-mail_outline"></span>
		 		</div>
		 		<div class="container_info">
			 		
				  <div class="collection">
				    <a href="#!" class="collection-item">Alan<span class="badge">1</span></a>
				    <a href="#!" class="collection-item">Alan<span class="new badge">4</span></a>
				    <a href="#!" class="collection-item">Alan</a>
				    <a href="#!" class="collection-item">Alan<span class="badge">14</span></a>
				  </div>
            
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Usuarios <span class="icon-user"></span>
		 		</div>
		 		<div class="container_info">
		 			
				  <div class="row">
				    <div class="col s12">
				      <ul class="tabs">
				        <li class="tab col s3"><a href="#test1">Lista</a></li>
				        <li class="tab col s3"><a href="#test2">Nuevo</a></li>
				        <li class="tab col s3"><a href="#test3">Editar</a></li>
				      </ul>
				    </div>
				    <div id="test1" class="col s12">
				    	<div class="container_info">
			 		
							<div class="collection">
							    <a href="#!" class="collection-item">Alan<span class="badge">1</span></a>
							    <a href="#!" class="collection-item">Alan<span class="new badge">4</span></a>
							    <a href="#!" class="collection-item">Alan</a>
							    <a href="#!" class="collection-item">Alan<span class="badge">14</span></a>
							</div>
			            
					 	</div>
				    </div>
				    <div id="test2" class="col s12">
				    	<div class="card_nuevo">
				    		<div class="userform">
							    <form class="col s12">
							      <div class="row">
							      	<div class="input-field col s12">
							          <i class="icon_dashboard icon-user2 prefix"></i>
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Nombre</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-user2 prefix"></i>
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Apellido</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-account_circle prefix"></i>
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Nombre de usuario</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Contraseña</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Validar contraseña</label>
							        </div>
							      </div>
							    </form>
							</div>
				    	</div>
				    </div>
				    <div id="test3" class="col s12">
				    	<div class="card_nuevo">
				    		<div class="userform">
							    <form class="col s12">
							      <div class="row">
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-search prefix"></i>
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Buscar usuario</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-account_circle prefix"></i>
							          <input id="icon_prefix" type="text" class="validate">
							          <label for="icon_prefix">Nombre de usuario</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Contraseña</label>
							        </div>
							        <div class="input-field col s12">
							          <i class="icon_dashboard icon-key3 prefix"></i>
							          <input id="icon_telephone" type="password" class="validate">
							          <label for="icon_telephone">Validar contraseña</label>
							        </div>
							      </div>
							    </form>
							</div>
				    	</div>
				    </div>
				  </div>
        
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m6 l4">
	 		<div class="my_card social_user_mail">
		 		<div class="card_title">
		 			Redes sociales <span class="icon-flow-tree"></span>
		 		</div>
		 		<div class="container_info">
		 			<div class="row">
					    <form class="col s12">
					      <div class="row">
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-facebook-with-circle prefix"></i>
					          <input id="icon_prefix" type="text" class="validate">
					          <label for="icon_prefix">Url facebook</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-twitter-with-circle prefix"></i>
					          <input id="icon_prefix" type="text" class="validate">
					          <label for="icon_prefix">Url twitter</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-google-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url google plus</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					      </div>
					    </form>
					</div>
		 		</div>
	 		</div>
	 	</div>

	 	<div class="card_container col s12 m12 l12">
	 		<div class="my_card portafolio_card">
		 		<div class="card_title">
		 			Portafolio <span class="icon-flow-tree"></span>
		 		</div>
		 		<div class="container_info">
		 			<div class="row">
					    <form class="col s12">
					      <div class="row">
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-facebook-with-circle prefix"></i>
					          <input id="icon_prefix" type="text" class="validate">
					          <label for="icon_prefix">Url facebook</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-twitter-with-circle prefix"></i>
					          <input id="icon_prefix" type="text" class="validate">
					          <label for="icon_prefix">Url twitter</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-google-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url google plus</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					        <div class="input-field col s12">
					          <i class="icon_dashboard icon-instagram-with-circle prefix"></i>
					          <input id="icon_telephone" type="text" class="validate">
					          <label for="icon_telephone">Url instagram</label>
					        </div>
					      </div>
					    </form>
					</div>
		 		</div>
	 		</div>
	 	</div>

    </div>
</div>