<div class="parallax-container">
	<div class="parallax"><img src="<?php echo BASE_URL ?>public/img/black-and-white-city-man-person.jpg"></div>
</div>

<section class="login-section">
	
	<div class="iniciar-session row">
	  <div class="content-form z-depth-3">
	    <div class="padding-user">
	      <div class="content-icon-user black">
	        <span class="icon-user"></span>
	      </div>
	    </div>
	    <div class="center-align titulo-registro">Iniciar sesion</div>
	    <form class="form-session" id="formlogin">
	      <div class="row">
	        <div class="input-field col s12 m12 l12">
	          <input id="first_name" type="text" class="validate" name="usuario_user">
	          <label for="first_name">Usuario</label>
	        </div>
	        <div class="input-field col s12 m12 l12">
	          <input id="password" type="password" class="validate" name="usuario_pass">
	          <label for="password">Password</label>
	        </div>
	      </div>
	      <button class="btn waves-effect teal darken-3 col s12 m12 l12" type="submit" name="action">Iniciar sesion</button>
	    </form>
	    <div class="recu-pass">
	    </div>
	  </div>
	</div>

</section>