<div class="container-info row container">
	<?php for ($i=0; $i < 3; $i++) { ?>
		<div class="container-pading col s12 m6 l4">
			<div class="card">
				<div title="<?php echo "pulpas antioxidantes"; ?>" class="Titulo-articulo center-align" >Nombre del servicio</div>
			  	<div class="container-item-img" >
					<img title="<?php echo "nombre-foto"; ?>" alt="Nombre de la foto" class="img-item" src="<?php echo BASE_URL.'public/img/pexels-photo-54370-compressor.jpeg' ?>">
				</div>
				<div class="card-content">
				  	<div class="activator center-align padding-arrow">
						<span title="Descripcion del servicio" class="activator icon-arrow-bold-right green darken-4 white-text"></span>
					</div>
				</div>
				<div class="card-reveal">
				  <span title="Caracteristicas" class="card-title grey-text text-darken-4"><strong>Caracteristicas</strong><i class="icon-keyboard_arrow_down right"></i></span>
				  <p></p>
				</div>
			</div>
		</div>
	<?php } ?>
</div>