<div class="container_nosotros">
	<div class="row container">
        <div class="col s12 m12 l12">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Nosotros</strong></div>
              <p><?php echo $this->nosotros[0]['portafolio_historia_cultura']; ?></p>
            </div>
          </div>
        </div>
    </div>
    <div class="row container">
        <div class="col s12 m12 l6">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Mision</strong></div>
              <p><?php echo $this->nosotros[0]['portafolio_mision']; ?></p>
            </div>
          </div>
        </div>

        <div class="col s12 m12 l6">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Vision</strong></div>
              <p><?php echo $this->nosotros[0]['portafolio_vision']; ?></p>
            </div>
          </div>
        </div>

    </div>
</div>