<div class="container_nosotros">
	<div class="row container">
        <div class="col s12 m12 l12">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Nosotros</strong></div>
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
          </div>
        </div>
    </div>
    <div class="row container">
        <div class="col s12 m12 l6">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Mision</strong></div>
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
          </div>
        </div>

        <div class="col s12 m12 l6">
          <div class="card white">
            <div class="card-content black-text">
              <div class="card-title center-align"><strong>Vision</strong></div>
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
          </div>
        </div>

    </div>
</div>