<section class="text-info-publica">
	<p class="container">
		<span class="inicio-text blue-text text-darken-1">H</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		ace algunos años las organizaciones reconocen lo importante de la administración de recursos de talento humano además del manejo de materias primas.
		La información está posicionada como uno de los recursos primordiales que las empresas tienen en la actualidad, de esta forma facilitan la toma de decisiones por esta razon se ha entiendido que la información no es un producto secundario del manejo empresarial. Por lo tanto, alimenta a los empresas y es uno de los factores determinantes del éxito o la ruina de la empresa
	</p>
</section>
<div class="parallax-container">
    <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/pexels-photo-52065.jpeg"></div>
</div>
<div class="row content-form-publica">
	<section class="col s12 m12 l12">
		<h5 class="center-align blue-text text-darken-1 font-publica" >Inscribe tu empresa</h3>
		<div class="row">
		    <form class="col s12" id="publica">
		    	<input name="nombre_usuario" type="hidden" value="<?php if (Session::get('autenticado')) {
		    		echo $_SESSION['nombre'].' '.$_SESSION['apellido'];
		    	}else{ echo "user";} ?>">
		      <div class="row">
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-account_circle prefix"></i>
		          <input id="icon-account_circle" type="text" class="validate" name="nombre_empresa">
		          <label for="icon-account_circle">Nombre de la empresa</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-domain prefix"></i>
		          <input id="icon-domain" type="text" class="validate" name="dir_ofi_central">
		          <label for="icon-domain">Dir. Oficina central</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-heart prefix"></i>
		          <input id="icon-heart" type="text" class="validate" name="fundacion">
		          <label for="icon-heart">Fundacion</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-user-tie prefix"></i>
		          <input id="icon-user-tie" type="text" class="validate" name="presidente">
		          <label for="icon-user-tie">Presidente</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-group_add prefix"></i>
		          	<p class="range-field">
				      <input value="0" type="range" id="test5" min="0" max="100" name="no_empleados">
				    </p>
		          <label for="icon-group_add">No. empleados</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-office prefix"></i>
		          <input id="icon-office" type="text" class="validate" name="dir_plan_indus">
		          <label for="icon-office">Dir. Plantas industriales</label>
		        </div>
		        <div class="input-field col s12 m12 l12">
		          <i class="icon-pencil prefix"></i>
		          <textarea id="icon-pencil" class="materialize-textarea" name="princ_operacion"></textarea>
		          <label for="icon-pencil">Principales operaciones</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-road prefix"></i>
		          <input id="icon-road" type="text" class="validate" name="dir_ofi_contacto">
		          <label for="icon-road">Dir. Oficina de contacto</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-infinite prefix"></i>
		          <input id="icon-infinite" type="text" class="validate" name="tipo_sociedad">
		          <label for="icon-infinite">Tipo de sociedad</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-file-text prefix"></i>
		          <input id="icon-file-rut" type="text" class="validate" name="rut">
		          <label for="icon-file-rut">Rut</label>
		        </div>
		        <div class="input-field col s12 m12 l12">
		          <i class="icon-local_offer prefix"></i>
		          <textarea id="icon-local_offer" class="materialize-textarea" name="tipo_productos"></textarea>
		          <label for="icon-local_offer">Tipos de producto</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-home4 prefix"></i>
		          <input id="icon-home4" type="text" class="validate" name="dir_domicilio">
		          <label for="icon-home4">Dir. domicilio legal</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-store_mall_directory prefix"></i>
		          <input id="icon-store_mall_directory" type="text" class="validate" name="dir_domicilio_comercial">
		          <label for="icon-store_mall_directory">Dir. Domicilio comercial</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-phone prefix"></i>
		          <input id="icon-phone" type="text" class="validate" name="tel">
		          <label for="icon-phone">Telefonos</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-print prefix"></i>
		          <input id="icon-print" type="text" class="validate" name="fax">
		          <label for="icon-print">Fax</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-markunread prefix"></i>
		          <input id="icon-markunread" type="text" class="validate" name="e_mail">
		          <label for="icon-markunread">E-mail</label>
		        </div>
		        <div class="input-field col s12 m6 l4">
				    <select  id="name_depato" name="departamento">
				    	<option value="" disabled selected>Elija una opcion</option>
				    <?php for ($h=0; $h < count($this->depto) ; $h++) { ?>
				    	<option value="<?php echo $this->depto[$h]['iddepartamento']; ?>"><?php echo $this->depto[$h]['nombre']; ?></option>
				    <?php } ?>
				    </select>
				    <label>Departamento</label>
			  	</div>
		        <div class="input-field col s12 m6 l4">
				    <select class="browser-default" id="name_mun" name="municipio">
				    	<option value="" disabled selected>Elija un Municipio</option>
				    </select>
			  	</div>
		        <div class="input-field col s12 m6 l4">
		          <i class="icon-list-numbered prefix"></i>
		          <input placeholder="Ej: Ferreteria" id="icon-list-numbered" type="text" class="validate" name="tipo_de_empresa">
		          <label for="icon-list-numbered">Tipo de empresa</label>
		        </div>
		      </div>
		      <button class="btn waves-effect transparent btn-contacto" type="submit" name="action">Enviar</button>
		    </form>
		</div>
	</section>
</div>
<div class="parallax-container">
    <div class="parallax"><img src="<?php echo BASE_URL ?>public/img/menu-restaurant-vintage-table.jpg"></div>
</div>