<section class="registro-conecta">
    <section class="registro-em-connecta">
      <div class=" white z-depth-3 registro-connecta">
        <div class="padding-user">
          <div class="content-icon-user black">
            <span class="icon-user"></span>
          </div>
        </div>
        <div class="center-align titulo-registro">Registro</div>
        <form class="form-registro row">
          <div class="row">
            <div class="input-field col s12 m12 l12">
              <input id="first_name" type="text" class="validate">
              <label for="first_name">Nombre</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input id="first_name" type="text" class="validate">
              <label for="first_name">Apellido</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input id="first_name" type="text" class="validate">
              <label for="first_name">Usuario</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input id="password" type="password" class="validate">
              <label for="password">Password</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input id="password" type="password" class="validate">
              <label for="password">Password</label>
            </div>
          </div>
          <button class="btn waves-effect teal darken-3 col s12 m12 l12" type="submit" name="action">Registrate</button>
        </form>
      </div>
    </section>
</section>