<div class="container_blog">
	<div class="aticle white z-depth-2">
		<div class="title_article center-align">
			<strong><?php echo $this->articulo['blog_titlulo'] ?></strong>
		</div>
		<div class="container_article">
			<?php echo $this->articulo['blog_contenido'] ?>
		</div>
		<div class="autor_article right-align">
			<span class="icon-subtext icon-account_circle"></span> 
			<?php echo $this->articulo['blog_autor'] ?>
		</div>
	</div>
</div>