<div class="container_aticle">
	<div class="close_article"></div>
	<div class="aticle white">
		<div class="title_article center-align">
			<strong>un titulo para el articulo</strong>
		</div>
		<div class="container_article">
			Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido
		</div>
		<div class="autor_article right-align">
			<span class="icon-subtext icon-account_circle"></span> <?php echo "un autor "; ?>
		</div>
	</div>
</div>
<div class="container_blog row">
	<?php for ($i=0; $i <  3; $i++) { ?>
		<div class="container_card_foro col s12 m6 l4">
			<div class="container_card white z-depth-3">
				<div class="card_foro">
					<div class="slider">
					    <ul class="slides">
					      <li>
					        <img src="http://lorempixel.com/580/250/nature/1"> <!-- random image -->
					        <div class="caption center-align">
					          <h3>This is our big Tagline!</h3>
					          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
					        </div>
					      </li>
					      <li>
					        <img src="http://lorempixel.com/580/250/nature/2"> <!-- random image -->
					        <div class="caption left-align">
					          <h3>Left Aligned Caption</h3>
					          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
					        </div>
					      </li>
					      <li>
					        <img src="http://lorempixel.com/580/250/nature/3"> <!-- random image -->
					        <div class="caption right-align">
					          <h3>Right Aligned Caption</h3>
					          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
					        </div>
					      </li>
					      <li>
					        <img src="http://lorempixel.com/580/250/nature/4"> <!-- random image -->
					        <div class="caption center-align">
					          <h3>This is our big Tagline!</h3>
					          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
					        </div>
					      </li>
					    </ul>
					</div>
				</div>
				<div class="container_previw_aricle">
					Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido
				</div>
				<div class="container_icons center-align">
					<span class="icon-subtext icon-account_circle"></span> <?php echo "un autor "; ?>
					<span class="icon-subtext icon-calendar2"></span> <?php echo " una fecha "; ?>
					<span class="icon-subtext icon-clapperboard"></span><?php echo " un tema"; ?>
				</div>
			</div>
		</div>
	<?php } ?>
	
</div>