<div class="container_blog row">
	<?php for ($i=0; $i <  count($this->blogfoto); $i++) { ?>
		<div class="container_card_foro col s12 m6 l4">
			<div class="container_card white z-depth-3">
				<div class="card_foro">
					<div class="slider">
					    <ul class="slides">
					      <li>
					        <img src="<?php echo BASE_URL. 'public/img/blog/'.$this->blogfoto[$i]['fotos_blog_nombre']?>"> <!-- random image -->
					        <div class="caption left-align">
					          <h4><?php echo $this->blogfoto[$i]['blog_titlulo']?></h4>
					        </div>
					      </li>
					    </ul>
					</div>
				</div>
				<div class="container_previw_aricle">
					<?php 
						$string = strlen ($this->blogfoto[$i]['blog_contenido']);
						if ($string <= 400) {
							echo $this->blogfoto[$i]['blog_contenido'];
						}else{
							echo substr($this->blogfoto[$i]['blog_contenido'], 0, 400) .'.... <a href="'.BASE_URL.'blog/articulo/'.$this->blogfoto[$i]['idblog'].'" id="verarticulo">Ver todo el articulo</a>';
						}
					?>
				</div>
				<div class="container_icons center-align">
					<span class="icon-subtext icon-account_circle"></span> <?php echo $this->blogfoto[$i]['blog_autor']; ?>
					<span class="icon-subtext icon-calendar2"></span> <?php echo $this->blogfoto[$i]['blog_fecha_pub']; ?>
					<span class="icon-subtext icon-clapperboard"></span><?php echo $this->blogfoto[$i]['blog_tema']; ?>
				</div>
			</div>
		</div>
	<?php } ?>
	
</div>