-- MySQL Script generated by MySQL Workbench
-- 03/26/16 02:45:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema em_conecta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `em_conecta` ;

-- -----------------------------------------------------
-- Schema em_conecta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `em_conecta` DEFAULT CHARACTER SET utf8 ;
USE `em_conecta` ;

-- -----------------------------------------------------
-- Table `em_conecta`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `em_conecta`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `departamento_iddepartamento` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`),
  CONSTRAINT `fk_municipio_departamento`
    FOREIGN KEY (`departamento_iddepartamento`)
    REFERENCES `em_conecta`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_municipio_departamento_idx` ON `em_conecta`.`municipio` (`departamento_iddepartamento` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `oficina_central` VARCHAR(200) NOT NULL,
  `fundacion` VARCHAR(200) NOT NULL,
  `presidente` VARCHAR(200) NOT NULL,
  `numero_de_empleados` VARCHAR(200) NOT NULL,
  `principales_operaciones` VARCHAR(500) NOT NULL,
  `plantas_industriales` VARCHAR(200) NOT NULL,
  `oficinas_de_contacto` VARCHAR(200) NOT NULL,
  `tipo_sociedad` VARCHAR(200) NOT NULL,
  `rut` VARCHAR(20) NOT NULL,
  `domicilio_legal` VARCHAR(200) NOT NULL,
  `domicilio_comercial` VARCHAR(200) NOT NULL,
  `telefonos` VARCHAR(200) NOT NULL,
  `fax` VARCHAR(200) NOT NULL,
  `e_mail` VARCHAR(200) NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  CONSTRAINT `fk_empresa_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `em_conecta`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rut_UNIQUE` ON `em_conecta`.`empresa` (`rut` ASC);

CREATE INDEX `fk_empresa_municipio1_idx` ON `em_conecta`.`empresa` (`municipio_idmunicipio` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NOT NULL,
  `valor` VARCHAR(50) NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  CONSTRAINT `fk_producto_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `em_conecta`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_producto_empresa1_idx` ON `em_conecta`.`producto` (`empresa_idempresa` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`tipo_producto` (
  `idtipo_producto` INT NOT NULL AUTO_INCREMENT,
  `tipo_producto__listado_nombres` TEXT NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idtipo_producto`),
  CONSTRAINT `fk_tipo_producto_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `em_conecta`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipo_producto_empresa1_idx` ON `em_conecta`.`tipo_producto` (`empresa_idempresa` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`admin_em_connecta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`admin_em_connecta` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `cod_act` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `activate` TINYINT(1) NOT NULL,
  `level` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `em_conecta`.`times_data_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`times_data_user` (
  `idtimes` INT NOT NULL AUTO_INCREMENT,
  `times_data_user_fecha_inicio` DATE NOT NULL,
  `times_data_user_fecha_fin` DATE NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idtimes`),
  CONSTRAINT `fk_times_data_user_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `em_conecta`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_times_data_user_empresa1_idx` ON `em_conecta`.`times_data_user` (`empresa_idempresa` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `name_tags` TEXT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtags`),
  CONSTRAINT `fk_tags_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `em_conecta`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tags_producto1_idx` ON `em_conecta`.`tags` (`producto_idproducto` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`tipo_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`tipo_empresa` (
  `idtipo_empresa` INT NOT NULL AUTO_INCREMENT,
  `tipo_empresa_nombre` VARCHAR(200) NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idtipo_empresa`),
  CONSTRAINT `fk_tipo_empresa_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `em_conecta`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipo_empresa_empresa1_idx` ON `em_conecta`.`tipo_empresa` (`empresa_idempresa` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`mapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`mapa` (
  `idmapa` INT NOT NULL AUTO_INCREMENT,
  `mapa_lat` VARCHAR(300) NOT NULL,
  `mapa_long` VARCHAR(300) NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idmapa`),
  CONSTRAINT `fk_mapa_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `em_conecta`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mapa_empresa1_idx` ON `em_conecta`.`mapa` (`empresa_idempresa` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`mensaje` (
  `idmensaje` INT NOT NULL AUTO_INCREMENT,
  `mensaje_nombre` VARCHAR(100) NOT NULL,
  `mensaje_apellido` VARCHAR(100) NOT NULL,
  `mensaje_asunto` VARCHAR(300) NOT NULL,
  `mensaje_email` VARCHAR(200) NOT NULL,
  `mensaje_mensaje` TEXT NOT NULL,
  PRIMARY KEY (`idmensaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `em_conecta`.`empresa_peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`empresa_peticion` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `oficina_central` VARCHAR(200) NOT NULL,
  `fundacion` VARCHAR(200) NOT NULL,
  `presidente` VARCHAR(200) NOT NULL,
  `numero_de_empleados` VARCHAR(200) NOT NULL,
  `principales_operaciones` VARCHAR(500) NOT NULL,
  `plantas_industriales` VARCHAR(200) NOT NULL,
  `oficinas_de_contacto` VARCHAR(200) NOT NULL,
  `tipo_sociedad` VARCHAR(200) NOT NULL,
  `rut` VARCHAR(20) NOT NULL,
  `domicilio_legal` VARCHAR(200) NOT NULL,
  `domicilio_comercial` VARCHAR(200) NOT NULL,
  `telefonos` VARCHAR(200) NOT NULL,
  `fax` VARCHAR(200) NOT NULL,
  `e_mail` VARCHAR(200) NOT NULL,
  `municipio_idmunicipio` VARCHAR(200) NOT NULL,
  `tipo_empresa_idtipo_empresa` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rut_UNIQUE` ON `em_conecta`.`empresa_peticion` (`rut` ASC);


-- -----------------------------------------------------
-- Table `em_conecta`.`portafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`portafolio` (
  `idportafolio` INT NOT NULL AUTO_INCREMENT,
  `portafolio_bienvenida` TEXT NOT NULL,
  `portafolio_marca` TEXT NOT NULL,
  `portafolio_historia_cultura` TEXT NOT NULL,
  `portafolio_inovation` TEXT NOT NULL,
  `portafolio_integration` TEXT NOT NULL,
  `portafolio_integrrity` TEXT NOT NULL,
  `portafolio_lista_servicios` TEXT NOT NULL,
  `portafolio_como_trabajamos` TEXT NOT NULL,
  `portafolio_nuestro_cerebro` TEXT NOT NULL,
  PRIMARY KEY (`idportafolio`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `em_conecta`.`otros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`otros` (
  `idotros` INT NOT NULL AUTO_INCREMENT,
  `otros_conecta_al_mundo` TEXT NOT NULL,
  `otros_efectividad` TEXT NOT NULL,
  `otros_productividad` TEXT NOT NULL,
  `otros_marketing` TEXT NOT NULL,
  `otros_datos` TEXT NOT NULL,
  `otros_nosotros` TEXT NOT NULL,
  `otros_mision` TEXT NOT NULL,
  `otros_vision` TEXT NOT NULL,
  `otros_en_que_creemos` TEXT NOT NULL,
  PRIMARY KEY (`idotros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `em_conecta`.`planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`planes` (
  `idplanes` INT NOT NULL AUTO_INCREMENT,
  `planes_titulo` VARCHAR(100) NOT NULL,
  `contenido` TEXT NOT NULL,
  `planes_title_inf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idplanes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `em_conecta`.`beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `em_conecta`.`beneficios` (
  `idbeneficios` INT NOT NULL AUTO_INCREMENT,
  `beneficios_lista_beneficios` TEXT NOT NULL,
  `planes_idplanes` INT NOT NULL,
  PRIMARY KEY (`idbeneficios`),
  CONSTRAINT `fk_beneficios_planes1`
    FOREIGN KEY (`planes_idplanes`)
    REFERENCES `em_conecta`.`planes` (`idplanes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_beneficios_planes1_idx` ON `em_conecta`.`beneficios` (`planes_idplanes` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `em_conecta`.`departamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `em_conecta`;
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Amazonas');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Antioquia');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Arauca');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Atlántico');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Bolívar');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Boyacá');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Caldas');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Caquetá');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Casanare');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Cauca');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Cesar');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Chocó');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Córdoba');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Cundinamarca');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Guainía');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Guaviare');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Huila');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'La guajira');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Magdalena');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Meta');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Nariño');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Norte Santander');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Putumayo');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Quindío');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Risaralda');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'San Andres y Providencia');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Santander');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Sucre');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Tolima');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Valle del Cauca');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Vaupés');
INSERT INTO `em_conecta`.`departamento` (`iddepartamento`, `nombre`) VALUES (DEFAULT, 'Vichada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `em_conecta`.`municipio`
-- -----------------------------------------------------
START TRANSACTION;
USE `em_conecta`;
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Leticia', 1);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Puerto Nariño', 1);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Barbosa', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Bello', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Caldas', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Caucasia', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Copacabana', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'El Retiro', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Envigado', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Girardota', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Guarne', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Itaquí', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Ceja', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Estrella', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Medellín', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Rionegro', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sabaneta', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Santa Fé de Antioquia', 2);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Arauca', 3);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Barranquilla', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Candelaria', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Luruaco', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ponedera', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sabanalarga', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Soledad', 4);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cartagena', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'El Carmen de Bolívar', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Magangué', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Mompós', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Simití', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Turbaco', 5);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Chiquinquirá', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Duitama', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Moniquirá', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Paipa', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Puerto Boyacá', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sogamoso', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tunja', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Villa de Leyva', 6);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Anserma', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Chinchiná', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Dorada', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Manizales', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Neira', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Salamina', 7);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Florencia', 8);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Yopal', 9);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Corinto', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Patía', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Piendamó', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Popayán', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Puerto Tejada', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Santander de Quilichao', 10);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Aguachica', 11);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Jagua de Iberico', 11);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Valledupar', 11);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Quibdó', 12);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cereté', 13);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Lorica', 13);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Montería', 13);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Planeta Rica', 13);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sahagún', 13);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Anapoima', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Bogotá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Bojacá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cajicá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Chía', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cota', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'El Colegio', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Facatativa', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Funza', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Fusagasugá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Gachancipá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Girardot', 11);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Calera', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Mesa', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Vega', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Madrid', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Mosquera', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Soacha', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sopó', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tenjo', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tocaima', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tocancipá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ubate', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Villeta', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Zipaquirá', 14);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Inírida', 15);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San José del Guaviare', 16);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Campoalegre', 17);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Garzón', 17);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Plata', 17);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Neiva', 17);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Pitalito', 17);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Riohacha', 18);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San Juan del Cesar', 18);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ciénaga', 19);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'El Banco', 19);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Fundación', 19);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Plato', 19);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Santa Marta', 19);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Acacías', 20);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Granada', 20);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Puerto López', 20);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San Martín', 20);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Villavicencio', 20);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ipiales', 21);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Pasto', 21);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tumaco', 21);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Túquerres', 21);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Barbosa', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Barichara ', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Barrancabermeja', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Bucaramanga', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Floridablanca', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Lebrija', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Girón', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Los Santos', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Piedecuesta', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ruitoque', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San Gil', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Socorro', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Vélez', 22);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Mocoa', 23);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Armenia', 24);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Calarcá', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Circasia', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Montenegro', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Quimbaya', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Salento', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Dosquebradas', 25);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'La Virginia', 26);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Marsella', 26);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Pereira', 26);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Santa Rosa de CabalSanta Rosa de Cabal', 26);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San Andres y Providencia', 26);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Corozal', 27);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'San Marcos', 27);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Sincelejo', 27);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tolú', 27);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Carmen de Apicalá', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Chaparral', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Espinal', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Flandes', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Guamo', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Honda', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ibagué', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Mariquita', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Melgar', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Purificación', 28);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Buenaventura', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Buga', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cali', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Candelaria', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cartago', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Palmira', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Tuluá', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Yumbo', 29);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Mitú', 30);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Puerto Carreño', 31);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Cúcuta', 32);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Ocaña', 32);
INSERT INTO `em_conecta`.`municipio` (`idmunicipio`, `nombre`, `departamento_iddepartamento`) VALUES (DEFAULT, 'Pamplona', 32);

COMMIT;


-- -----------------------------------------------------
-- Data for table `em_conecta`.`admin_em_connecta`
-- -----------------------------------------------------
START TRANSACTION;
USE `em_conecta`;
INSERT INTO `em_conecta`.`admin_em_connecta` (`idadmin`, `nombre`, `apellido`, `cedula`, `cod_act`, `usuario`, `pass`, `activate`, `level`) VALUES (DEFAULT, 'Christian', 'Portilla', '1085250898', '1', 'Christopher', 'Clshiorzf', 1, '3');

COMMIT;

