-- MySQL Script generated by MySQL Workbench
-- 04/19/16 19:32:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `empresa` ;

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8 ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`productos_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`productos_tipo` (
  `idproductos_tipo` INT NOT NULL AUTO_INCREMENT,
  `productos_tipo_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idproductos_tipo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `productos_tipo_nombre_UNIQUE` ON `empresa`.`productos_tipo` (`productos_tipo_nombre` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `producto_descripcion` TEXT NOT NULL,
  `producto_valor` VARCHAR(45) NOT NULL,
  `producto_nombre` VARCHAR(100) NOT NULL,
  `productos_tipo_idproductos_tipo` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  CONSTRAINT `fk_producto_productos_tipo1`
    FOREIGN KEY (`productos_tipo_idproductos_tipo`)
    REFERENCES `empresa`.`productos_tipo` (`idproductos_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_producto_productos_tipo1_idx` ON `empresa`.`producto` (`productos_tipo_idproductos_tipo` ASC);

CREATE UNIQUE INDEX `producto_nombre_UNIQUE` ON `empresa`.`producto` (`producto_nombre` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`blog` (
  `idblog` INT NOT NULL AUTO_INCREMENT,
  `blog_titlulo` VARCHAR(100) NOT NULL,
  `blog_contenido` TEXT NOT NULL,
  `blog_fecha_pub` DATE NOT NULL,
  `blog_autor` VARCHAR(100) NOT NULL,
  `blog_tema` VARCHAR(100) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idblog`),
  CONSTRAINT `fk_blog_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `empresa`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_blog_producto1_idx` ON `empresa`.`blog` (`producto_idproducto` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`fotos` (
  `idfotos` INT NOT NULL AUTO_INCREMENT,
  `fotos_name` TEXT NOT NULL,
  `fotos_alt` VARCHAR(100) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  CONSTRAINT `fk_fotos_producto`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `empresa`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fotos_producto_idx` ON `empresa`.`fotos` (`producto_idproducto` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `tags_lsitado_tags` TEXT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtags`),
  CONSTRAINT `fk_tags_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `empresa`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tags_producto1_idx` ON `empresa`.`tags` (`producto_idproducto` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_nombre` VARCHAR(100) NOT NULL,
  `usuario_apellido` VARCHAR(100) NOT NULL,
  `usuario_usuario` VARCHAR(100) NOT NULL,
  `usuario_pass` VARCHAR(100) NOT NULL,
  `usuario_estate` VARCHAR(100) NOT NULL,
  `usuario_activate` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuario_usuario_UNIQUE` ON `empresa`.`usuario` (`usuario_usuario` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`fotos_blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`fotos_blog` (
  `idfotos_blog` INT NOT NULL AUTO_INCREMENT,
  `fotos_blog_nombre` TEXT NOT NULL,
  `fotos_blog_alt` VARCHAR(100) NOT NULL,
  `blog_idblog` INT NOT NULL,
  PRIMARY KEY (`idfotos_blog`),
  CONSTRAINT `fk_fotos_blog_blog1`
    FOREIGN KEY (`blog_idblog`)
    REFERENCES `empresa`.`blog` (`idblog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fotos_blog_blog1_idx` ON `empresa`.`fotos_blog` (`blog_idblog` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`portafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`portafolio` (
  `idportafolio` INT NOT NULL AUTO_INCREMENT,
  `portafolio_telefonos` VARCHAR(100) NOT NULL,
  `portafolio_logo_name` VARCHAR(100) NOT NULL,
  `portafolio_bienvenido` TEXT NOT NULL,
  `portafolio_innovacion` TEXT NOT NULL,
  `portafolio_integracion` TEXT NOT NULL,
  `portafolio_integridad` TEXT NOT NULL,
  `portafolio_historia_cultura` TEXT NOT NULL,
  `portafolio_mision` TEXT NOT NULL,
  `portafolio_vision` TEXT NOT NULL,
  `portafolio_marca` TEXT NOT NULL,
  `portafolio_como_trabajamos` TEXT NOT NULL,
  `portafolio_direccion` VARCHAR(100) NOT NULL,
  `portafolio_latitud` VARCHAR(200) NULL,
  `portafolio_longitud` VARCHAR(200) NULL,
  PRIMARY KEY (`idportafolio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`servicios` (
  `idservicios` INT NOT NULL AUTO_INCREMENT,
  `servicios_nombre` VARCHAR(100) NOT NULL,
  `servicios_descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idservicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`fotos_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`fotos_servicios` (
  `idfotos_servicios` INT NOT NULL AUTO_INCREMENT,
  `fotos_servicios_name` TEXT NOT NULL,
  `fotos_servicios_alt` VARCHAR(100) NOT NULL,
  `servicios_idservicios` INT NOT NULL,
  PRIMARY KEY (`idfotos_servicios`),
  CONSTRAINT `fk_fotos_servicios_servicios1`
    FOREIGN KEY (`servicios_idservicios`)
    REFERENCES `empresa`.`servicios` (`idservicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fotos_servicios_servicios1_idx` ON `empresa`.`fotos_servicios` (`servicios_idservicios` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`favi_icon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`favi_icon` (
  `idlogo` INT NOT NULL AUTO_INCREMENT,
  `logo_nombre` TEXT NOT NULL,
  PRIMARY KEY (`idlogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`social` (
  `idsocial` INT NOT NULL AUTO_INCREMENT,
  `social_nombre` VARCHAR(100) NOT NULL,
  `social_url` TEXT NULL,
  PRIMARY KEY (`idsocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`mensaje` (
  `idmensaje` INT NOT NULL AUTO_INCREMENT,
  `mensaje_nombre` VARCHAR(100) NOT NULL,
  `mensaje_apellido` VARCHAR(100) NOT NULL,
  `mensaje_asunto` VARCHAR(100) NOT NULL,
  `mensaje_email` VARCHAR(100) NOT NULL,
  `mensaje_mensaje` TEXT NOT NULL,
  PRIMARY KEY (`idmensaje`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `empresa`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `empresa`;
INSERT INTO `empresa`.`usuario` (`idusuario`, `usuario_nombre`, `usuario_apellido`, `usuario_usuario`, `usuario_pass`, `usuario_estate`, `usuario_activate`) VALUES (DEFAULT, 'administrador', 'administrador', 'admin', 'admin', '1', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `empresa`.`social`
-- -----------------------------------------------------
START TRANSACTION;
USE `empresa`;
INSERT INTO `empresa`.`social` (`idsocial`, `social_nombre`, `social_url`) VALUES (DEFAULT, 'Facebook', NULL);
INSERT INTO `empresa`.`social` (`idsocial`, `social_nombre`, `social_url`) VALUES (DEFAULT, 'Twitter', NULL);
INSERT INTO `empresa`.`social` (`idsocial`, `social_nombre`, `social_url`) VALUES (DEFAULT, 'Google plus', NULL);
INSERT INTO `empresa`.`social` (`idsocial`, `social_nombre`, `social_url`) VALUES (DEFAULT, 'Instagram', NULL);

COMMIT;

